import { business } from "@/data/business";
import { ButtonLink } from "@/components/ui";
import { pageMetadata } from "@/lib/seo";

export const metadata = pageMetadata("Visit & contact", "Find Aaram Fusion Cafe at 664 Miles Platting Road, Rochedale QLD 4123. Get directions, check ordering options and review the latest visiting information.", "/visit/");

export default function VisitPage() {
  return <>
    <section className="page-heading wrap"><p className="eyebrow">AARAM FUSION / ROCHEDALE</p><div className="page-heading-grid"><h1>See you<br /><em>in Rochedale.</em></h1><p>A café stop on<br />Miles Platting Road,<br />Brisbane’s southside.</p></div></section>
    <section className="location-feature wrap" aria-labelledby="location-title"><div className="address-panel"><span className="eyebrow">THE LISTED ADDRESS</span><h2 id="location-title">664<br /><span>Miles Platting<br />Road.</span></h2><p>Rochedale, QLD 4123<br />Brisbane, Australia</p><ButtonLink href={business.mapsUrl} external>Directions on Google Maps</ButtonLink></div><div className="visit-information"><section><p className="eyebrow">BEFORE YOU VISIT</p><h2>Opening hours</h2><p>Restaurant opening hours are awaiting confirmation. Delivery-platform hours may differ from dine-in hours, so check before making a special trip.</p><a className="text-link" href={business.orderUrl}>Check the current Uber Eats listing ↗</a></section><section><p className="eyebrow">GET IN TOUCH</p><h2>Contact details</h2><p>A current direct phone number and email have not yet been verified for this website. Confirm visiting arrangements through the restaurant’s current business listing before heading over.</p><p className="quiet-note">We’ll add direct contact details once confirmed.</p></section></div></section>
    <section className="visit-faq wrap" aria-labelledby="faq-title"><div><p className="eyebrow">A FEW USEFUL DETAILS</p><h2 id="faq-title">Before<br />you head out.</h2></div><div className="faq-list"><details><summary>Can I order online?<span aria-hidden="true">+</span></summary><p>Aaram Fusion Cafe has an <a href={business.orderUrl}>Uber Eats listing</a>. Enter your address there to check current availability, prices and delivery options.</p></details><details><summary>Can I book a table?<span aria-hidden="true">+</span></summary><p>A reservation service has not been verified. This website cannot take bookings. Please confirm arrangements directly with the restaurant before visiting.</p></details><details><summary>What about dietary requirements?<span aria-hidden="true">+</span></summary><p>Dietary options and allergen information need confirmation from the restaurant. Check ingredients and preparation before ordering; the menu preview is not an allergen guide.</p></details><details><summary>Is parking or step-free access available?<span aria-hidden="true">+</span></summary><p>Parking and step-free access have not yet been verified. Confirm the facilities you need before travelling.</p></details></div></section>
  </>;
}
